// Synchronous
export const ADD_NODE = 'ADD_NODE';
export const REMOVE_NODE = 'REMOVE_NODE';
export const UPDATE_ELEMENTS = 'UPDATE_ELEMENTS';
export const SELECT_NODE = 'SELECT_NODE';

// Async
export const FETCH_GRAPH_REQUEST = 'FETCH_GRAPH_REQUEST';
export const FETCH_GRAPH_SUCCESS = 'FETCH_GRAPH_SUCCESS';
export const FETCH_GRAPH_FAILURE = 'FETCH_GRAPH_FAILURE';

export const UPDATE_GRAPH_REQUEST = 'UPDATE_GRAPH_REQUEST';
export const UPDATE_GRAPH_SUCCESS = 'UPDATE_GRAPH_SUCCESS';
export const UPDATE_GRAPH_FAILURE = 'UPDATE_GRAPH_FAILURE';
