// Synchronous
export const ADD_NODE = 'ADD_NODE';
export const REMOVE_NODE = 'REMOVE_NODE';
export const UPDATE_NODE = 'UPDATE_NODE';
export const UPDATE_ELEMENTS = 'UPDATE_ELEMENTS';
export const SELECT_NODE = 'SELECT_NODE';
export const ADD_COMPLETED_NODE = 'ADD_COMPLETED_NODE';
export const REMOVE_COMPLETED_NODE = 'REMOVE_COMPLETED_NODE';
export const TOGGLE_GRAPH_DETAILS = 'TOGGLE_GRAPH_DETAILS';
export const UPDATE_PROGRESS_MODE = 'UPDATE_PROGRESS_MODE';

// Async
export const FETCH_GRAPH_REQUEST = 'FETCH_GRAPH_REQUEST';
export const FETCH_GRAPH_SUCCESS = 'FETCH_GRAPH_SUCCESS';
export const FETCH_GRAPH_FAILURE = 'FETCH_GRAPH_FAILURE';

export const FETCH_COMPLETED_NODES_REQUEST = 'FETCH_COMPLETED_NODES_REQUEST';
export const FETCH_COMPLETED_NODES_SUCCESS = 'FETCH_COMPLETED_NODES_SUCCESS';
export const FETCH_COMPLETED_NODES_FAILURE = 'FETCH_COMPLETED_NODES_FAILURE';
